# Generated by Django 2.2.5 on 2019-09-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=1024)),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
