# Generated by Django 2.2.5 on 2019-11-19 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='review_number',
            field=models.IntegerField(default=0, verbose_name='Количество отзывов'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Достопримечательность'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
