# Generated by Django 2.2.5 on 2019-11-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_auto_20191119_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='review_number',
        ),
    ]
